shared:
  audio:
    RTPJitterBuffer: rtpjitterbuffer name=audio_buffer do-lost=1 latency=200
  video:
    RTPJitterBuffer: rtpjitterbuffer name=video_buffer do-lost=1 add-reference-timestamp-meta=true latency=200
    rawFormat: video/x-raw,format=I420,colorimetry=bt601,chroma-site=jpeg,pixel-aspect-ratio=1/1
    constraint:
      format: >-
        {{.Convert}} !
        capsfilter caps={{.VideoFormat}}
      formatFramerate: >-
        {{.Convert}} !
        videorate !
        capsfilter caps={{.VideoFormatFramerate}} caps-change-mode=1
      formatFramerateResolution: >-
        {{.Convert}} !
        videorate !
        capsfilter caps={{.VideoFormatFramerateResolution}} caps-change-mode=1
  queue:
    base: queue
    short: queue max-size-buffers=0 max-size-bytes=0 max-size-time=75000000
    leaky: queue leaky=2
    long: queue max-size-buffers=0 max-size-bytes=0 max-size-time=3000000000 
opus:
  encoding: "OPUS"
  rtp:
    caps: application/x-rtp,payload=111,encoding-name=OPUS
    pay: rtpopuspay
    depay: >-
      rtpopusdepay !
      opusparse
  decoder: opusdec
  encoder: >-
    opusenc name={{.Name}}
    bitrate={{.DefaultBitrate}}
    audio-type=2048
    bitrate-type=1
    perfect-timestamp=false
vp8:
  encoding: "VP8"
  muxer: "matroskamux"
  extension: "mkv"
  rtp:
    caps: application/x-rtp,encoding-name=VP8-DRAFT-IETF-01
    pay: rtpvp8pay min-ptime=30000000
    depay: rtpvp8depay
  decoder: vp8dec min-force-key-unit-interval=3000000000 discard-corrupted-frames=true qos=true
  encoder: >-
    vp8enc name={{.Name}}
    target-bitrate={{.DefaultBitrate}}
    deadline=1
    end-usage=1
    undershoot=95
    keyframe-max-dist=999999
    max-quantizer=56
    min-force-key-unit-interval=3000000000
    qos=true
x264:
  encoding: "H264"
  muxer: "mp4mux"
  extension: "mp4"
  rtp:
    caps: application/x-rtp,encoding-name=H264
    pay: rtph264pay
    depay: >-
      rtph264depay !
      h264parse !
      h264timestamper
  decoder: avdec_h264 min-force-key-unit-interval=3000000000 discard-corrupted-frames=true qos=true
  encoder: >-
    x264enc name={{.Name}} pass=17
    bitrate={{.DefaultKBitrate}}
    pass=pass1
    multipass-cache-file={{.Folder}}/cache/{{.FilePrefix}}.{{.Name}}.x264_pass.log 
    speed-preset=ultrafast
    min-force-key-unit-interval=3000000000
    qos=true !
    video/x-h264, profile=main ! 
    h264parse
nv264:
  encoding: "H264"
  muxer: "mp4mux"
  extension: "mp4"
  rtp:
    caps: application/x-rtp,encoding-name=H264
    pay: rtph264pay
    depay: >-
      rtph264depay !
      h264parse !
      h264timestamper
  decoder: nvh264sldec qos=true
  encoder: >-
    nvh264enc name={{.Name}}
    bitrate={{.DefaultKBitrate}}
    preset=5
    rc-mode=7
    rc-lookahead=0
    qos=true !
    video/x-h264, profile=main !
    h264parse