shared:
  audio:
    RTPJitterBuffer: rtpjitterbuffer name=audio_buffer latency=200
  video:
    RTPJitterBuffer: rtpjitterbuffer name=video_buffer latency=200
    rawFormat: video/x-raw,format=I420,pixel-aspect-ratio=1/1
    constraint:
      format: >-
        {{.Convert}} !
        capsfilter caps={{.VideoFormat}}
      formatFramerate: >-
        {{.Convert}} !
        videorate !
        capsfilter caps={{.VideoFormatFramerate}} caps-change-mode=1
      formatFramerateResolution: >-
        {{.Convert}} !
        videorate !
        capsfilter caps={{.VideoFormatFramerateResolution}} caps-change-mode=1
    timeOverlay: timeoverlay time-mode=1
  queue:
    base: queue max-size-buffers=0 max-size-bytes=0 max-size-time=200000000
    leaky: queue leaky=2 max-size-buffers=0 max-size-bytes=0 max-size-time=200000000
    short: queue max-size-buffers=0 max-size-bytes=0 max-size-time=75000000
    long: queue max-size-buffers=0 max-size-bytes=0 max-size-time=3000000000 
opus:
  encoding: "OPUS"
  muxer: "oggmux"
  extension: "ogg"
  rtp:
    caps: application/x-rtp,media=audio,clock-rate=48000,payload=111,encoding-name=OPUS
    pay: rtpopuspay pt=111 mtu=1200
    depay: rtpopusdepay
  decoder: opusdec
  encoder: >-
    opusenc name={{.Name}}
    bitrate={{.DefaultBitrate}}
    audio-type=2048
    bitrate-type=1
    perfect-timestamp=false
vp8:
  encoding: "VP8"
  muxer: "matroskamux"
  extension: "mkv"
  rtp:
    caps: application/x-rtp,media=video,clock-rate=90000,payload=96,encoding-name=VP8-DRAFT-IETF-01
    pay: rtpvp8pay pt=96 min-ptime=30000000
    depay: rtpvp8depay request-keyframe=true
  decoder: >-
    vp8dec
    discard-corrupted-frames=true
    min-force-key-unit-interval=500000000
  encoder: >-
    vp8enc name={{.Name}}
    target-bitrate={{.DefaultBitrate}}
    deadline=1
    end-usage=1
    undershoot=95
    keyframe-max-dist=999999
    max-quantizer=56
    min-force-key-unit-interval=500000000
x264:
  encoding: "H264"
  muxer: "mp4mux"
  extension: "mp4"
  rtp:
    caps: application/x-rtp,media=video,clock-rate=90000,payload=125,encoding-name=H264
    pay: rtph264pay pt=125 mtu=1200 aggregate-mode=zero-latency
    depay: >-
      rtph264depay request-keyframe=true !
      h264parse config-interval=-1 !
      h264timestamper
  decoder: >-
    avdec_h264
    discard-corrupted-frames=true
    min-force-key-unit-interval=500000000
  encoder: >-
    x264enc name={{.Name}}
    bitrate={{.DefaultKBitrate}}
    pass=17
    pass=pass1
    multipass-cache-file={{.Folder}}/cache/{{.FilePrefix}}.{{.Name}}.x264_pass.log 
    speed-preset=ultrafast
    tune=zerolatency
    threads=4
    key-int-max=256
    b-adapt=false
    vbv-buf-capacity=120
    min-force-key-unit-interval=500000000 !
    video/x-h264, profile=constrained-baseline ! 
    h264parse
nv264:
  encoding: "H264"
  muxer: "mp4mux"
  extension: "mp4"
  rtp:
    caps: application/x-rtp,media=video,clock-rate=90000,payload=125,encoding-name=H264
    pay: rtph264pay pt=125 mtu=1200 aggregate-mode=zero-latency
    depay: >-
      rtph264depay request-keyframe=true !
      h264parse config-interval=-1 !
      h264timestamper
  decoder: >-
    nvh264sldec
    discard-corrupted-frames=true
    min-force-key-unit-interval=500000000
  encoder: >-
    nvh264enc name={{.Name}}
    bitrate={{.DefaultKBitrate}}
    preset=low-latency-hp
    rc-mode=cbr-ld-hq
    zerolatency=true
    min-force-key-unit-interval=500000000
    rc-lookahead=0 !
    video/x-h264, profile=constrained-baseline !
    h264parse