common:
  mtu: 1460
  encoderControlPeriod: 5000
  twccInterval: 30
audio:
  defaultBitrate: 64000
  minBitrate: 32000
  maxBitrate: 64000
video:
  defaultBitrate: 300000
  minBitrate: 150000
  maxBitrate: 1500000